//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(WebConsultas.Models.WebConsultasContext),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsc4d16458c6a3daebf1c85ed708c062156befd0972aa8fb3e6059865a510838f2))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework 6 Power Tools", "0.9.2.0")]
    internal sealed class ViewsForBaseEntitySetsc4d16458c6a3daebf1c85ed708c062156befd0972aa8fb3e6059865a510838f2 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "c4d16458c6a3daebf1c85ed708c062156befd0972aa8fb3e6059865a510838f2"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "CodeFirstDatabase.Bairro")
            {
                return GetView0();
            }

            if (extentName == "CodeFirstDatabase.Cidade")
            {
                return GetView1();
            }

            if (extentName == "CodeFirstDatabase.Estado")
            {
                return GetView2();
            }

            if (extentName == "CodeFirstDatabase.Cargo")
            {
                return GetView3();
            }

            if (extentName == "CodeFirstDatabase.Endereco")
            {
                return GetView4();
            }

            if (extentName == "CodeFirstDatabase.Funcionario")
            {
                return GetView5();
            }

            if (extentName == "CodeFirstDatabase.TelefonesFunc")
            {
                return GetView6();
            }

            if (extentName == "WebConsultasContext.bairros")
            {
                return GetView7();
            }

            if (extentName == "WebConsultasContext.cidades")
            {
                return GetView8();
            }

            if (extentName == "WebConsultasContext.estados")
            {
                return GetView9();
            }

            if (extentName == "WebConsultasContext.cargos")
            {
                return GetView10();
            }

            if (extentName == "WebConsultasContext.enderecos")
            {
                return GetView11();
            }

            if (extentName == "WebConsultasContext.funcionarios")
            {
                return GetView12();
            }

            if (extentName == "WebConsultasContext.telefones")
            {
                return GetView13();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Bairro.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Bairro
        [CodeFirstDatabaseSchema.Bairro](T1.Bairro_idBairro, T1.Bairro_descricao, T1.[Bairro.Cidade_idCidade])
    FROM (
        SELECT 
            T.idBairro AS Bairro_idBairro, 
            T.descricao AS Bairro_descricao, 
            T.Cidade_idCidade AS [Bairro.Cidade_idCidade], 
            True AS _from0
        FROM WebConsultasContext.bairros AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Cidade.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Cidade
        [CodeFirstDatabaseSchema.Cidade](T1.Cidade_idCidade, T1.Cidade_descricao, T1.[Cidade.Estado_idEstado])
    FROM (
        SELECT 
            T.idCidade AS Cidade_idCidade, 
            T.descricao AS Cidade_descricao, 
            T.Estado_idEstado AS [Cidade.Estado_idEstado], 
            True AS _from0
        FROM WebConsultasContext.cidades AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Estado.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Estado
        [CodeFirstDatabaseSchema.Estado](T1.Estado_idEstado, T1.Estado_descricao)
    FROM (
        SELECT 
            T.idEstado AS Estado_idEstado, 
            T.descricao AS Estado_descricao, 
            True AS _from0
        FROM WebConsultasContext.estados AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Cargo.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Cargo
        [CodeFirstDatabaseSchema.Cargo](T1.Cargo_idCargo, T1.Cargo_descricao)
    FROM (
        SELECT 
            T.idCargo AS Cargo_idCargo, 
            T.descricao AS Cargo_descricao, 
            True AS _from0
        FROM WebConsultasContext.cargos AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Endereco.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Endereco
        [CodeFirstDatabaseSchema.Endereco](T1.Endereco_idEndereco, T1.Endereco_rua, T1.Endereco_numero, T1.Endereco_complemento, T1.Endereco_obs, T1.[Endereco.Estado_idEstado])
    FROM (
        SELECT 
            T.idEndereco AS Endereco_idEndereco, 
            T.rua AS Endereco_rua, 
            T.numero AS Endereco_numero, 
            T.complemento AS Endereco_complemento, 
            T.obs AS Endereco_obs, 
            T.Estado_idEstado AS [Endereco.Estado_idEstado], 
            True AS _from0
        FROM WebConsultasContext.enderecos AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Funcionario.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Funcionario
        [CodeFirstDatabaseSchema.Funcionario](T1.Funcionario_idFuncionario, T1.Funcionario_nome, T1.Funcionario_salario, T1.Funcionario_dataDemi, T1.[Funcionario.Cargo_idCargo], T1.[Funcionario.Endereco_idEndereco])
    FROM (
        SELECT 
            T.idFuncionario AS Funcionario_idFuncionario, 
            T.nome AS Funcionario_nome, 
            T.salario AS Funcionario_salario, 
            T.dataDemi AS Funcionario_dataDemi, 
            T.Cargo_idCargo AS [Funcionario.Cargo_idCargo], 
            T.Endereco_idEndereco AS [Funcionario.Endereco_idEndereco], 
            True AS _from0
        FROM WebConsultasContext.funcionarios AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.TelefonesFunc.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing TelefonesFunc
        [CodeFirstDatabaseSchema.TelefonesFunc](T1.TelefonesFunc_idTelefone, T1.TelefonesFunc_numero, T1.[TelefonesFunc.Funcionario_idFuncionario])
    FROM (
        SELECT 
            T.idTelefone AS TelefonesFunc_idTelefone, 
            T.numero AS TelefonesFunc_numero, 
            T.Funcionario_idFuncionario AS [TelefonesFunc.Funcionario_idFuncionario], 
            True AS _from0
        FROM WebConsultasContext.telefones AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WebConsultasContext.bairros.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing bairros
        [WebConsultas.Models.Bairro](T1.Bairro_idBairro, T1.Bairro_descricao, T1.[Bairro.Cidade_idCidade])
    FROM (
        SELECT 
            T.idBairro AS Bairro_idBairro, 
            T.descricao AS Bairro_descricao, 
            T.Cidade_idCidade AS [Bairro.Cidade_idCidade], 
            True AS _from0
        FROM CodeFirstDatabase.Bairro AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WebConsultasContext.cidades.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing cidades
        [WebConsultas.Models.Cidade](T1.Cidade_idCidade, T1.Cidade_descricao, T1.[Cidade.Estado_idEstado])
    FROM (
        SELECT 
            T.idCidade AS Cidade_idCidade, 
            T.descricao AS Cidade_descricao, 
            T.Estado_idEstado AS [Cidade.Estado_idEstado], 
            True AS _from0
        FROM CodeFirstDatabase.Cidade AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WebConsultasContext.estados.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing estados
        [WebConsultas.Models.Estado](T1.Estado_idEstado, T1.Estado_descricao)
    FROM (
        SELECT 
            T.idEstado AS Estado_idEstado, 
            T.descricao AS Estado_descricao, 
            True AS _from0
        FROM CodeFirstDatabase.Estado AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WebConsultasContext.cargos.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing cargos
        [WebConsultas.Models.Cargo](T1.Cargo_idCargo, T1.Cargo_descricao)
    FROM (
        SELECT 
            T.idCargo AS Cargo_idCargo, 
            T.descricao AS Cargo_descricao, 
            True AS _from0
        FROM CodeFirstDatabase.Cargo AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WebConsultasContext.enderecos.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing enderecos
        [WebConsultas.Models.Endereco](T1.Endereco_idEndereco, T1.Endereco_rua, T1.Endereco_numero, T1.Endereco_complemento, T1.Endereco_obs, T1.[Endereco.Estado_idEstado])
    FROM (
        SELECT 
            T.idEndereco AS Endereco_idEndereco, 
            T.rua AS Endereco_rua, 
            T.numero AS Endereco_numero, 
            T.complemento AS Endereco_complemento, 
            T.obs AS Endereco_obs, 
            T.Estado_idEstado AS [Endereco.Estado_idEstado], 
            True AS _from0
        FROM CodeFirstDatabase.Endereco AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WebConsultasContext.funcionarios.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing funcionarios
        [WebConsultas.Models.Funcionario](T1.Funcionario_idFuncionario, T1.Funcionario_nome, T1.Funcionario_salario, T1.Funcionario_dataDemi, T1.[Funcionario.Cargo_idCargo], T1.[Funcionario.Endereco_idEndereco])
    FROM (
        SELECT 
            T.idFuncionario AS Funcionario_idFuncionario, 
            T.nome AS Funcionario_nome, 
            T.salario AS Funcionario_salario, 
            T.dataDemi AS Funcionario_dataDemi, 
            T.Cargo_idCargo AS [Funcionario.Cargo_idCargo], 
            T.Endereco_idEndereco AS [Funcionario.Endereco_idEndereco], 
            True AS _from0
        FROM CodeFirstDatabase.Funcionario AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WebConsultasContext.telefones.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing telefones
        [WebConsultas.Models.TelefonesFunc](T1.TelefonesFunc_idTelefone, T1.TelefonesFunc_numero, T1.[TelefonesFunc.Funcionario_idFuncionario])
    FROM (
        SELECT 
            T.idTelefone AS TelefonesFunc_idTelefone, 
            T.numero AS TelefonesFunc_numero, 
            T.Funcionario_idFuncionario AS [TelefonesFunc.Funcionario_idFuncionario], 
            True AS _from0
        FROM CodeFirstDatabase.TelefonesFunc AS T
    ) AS T1");
        }
    }
}
